### ISSUE TITLE
[Bug]: Unable to locate a class or view for component [chatgpt-svg].

### ISSUE THREAD

**Issue by Palria** [icetalker/filament-chatgpt-bot#5]
### What happened?

Unable to locate a class or view for component [chatgpt-svg].

### How to reproduce the bug

<?php

// config for Icetalker/FilamentChatgptBot
return [
    'enable' => true,

    'openai' => [
        'api_key' => env('OPENAI_API_KEY'),
        'organization' => env('OPENAI_ORGANIZATION'),
    ],
    
    'proxy'=> env('OPENAI_PROXY'),

];

if enabled =true
it will show this error.

### Package Version

0.1.2

### PHP Version

8.1

### Laravel Version

10.0

**Comment by sairiz** [comment]
Same with me. Appears on fresh installation

**Comment by nlvpatrick** [comment]
Unable to locate a class or view for component [chatgpt-svg].

**Comment by icetalker** [comment]
fixed
